### ISSUE TITLE
Project page stuck

### ISSUE THREAD

**Issue by Jakestudiofriday** [markendley/lme#10]
Project pages seem stuck when you open them - the scroll doesn't work smoothly

**Comment by markendley** [comment]
fixed

**Comment by Jakestudiofriday** [comment]
Still getting stuck

**Comment by markendley** [comment]
damn, are you sure?

I tested it again after clearing cache on Safari and Chrome.

Do you wait for the window to finish loading or do you just attempt as soon as you see the gallery?

**Comment by Jakestudiofriday** [comment]
Hey, so do think the problem is with the page not being fully loaded? - the page looks like it is loaded.

Could you add animations as you scroll?
