### ISSUE TITLE
Scroll bar overlapping images

### ISSUE THREAD

**Issue by Jakestudiofriday** [markendley/lme#11]
Scroll bar overlapping images - https://www.seesawstudio.com.au/junction-moama/
<img width="1360" alt="Screen Shot 2020-01-31 at 12 07 51 pm" src="https://user-images.githubusercontent.com/57921772/73504262-e3399500-4422-11ea-9fc4-d7079c68b91f.png">

**Comment by markendley** [comment]
fixed
