### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/lme#15]
When you scroll across, there is a jump when you get to the end. Can we please stop the third image from jumping up - this doesn't 'have any images jumping up

**Comment by markendley** [comment]
Sorry I don't get that on Chrome or iOS...

You mean when you scroll super fast?
When you mean "jump" the image just appears? or does it come in from the bottom and rise up really quickly?

Need a video or something

**Comment by LaraStudioFriday** [comment]
It's when you try and scroll down - last image jumps. Have taken a video for you. will chat it to you.

**Comment by markendley** [comment]
Oh that!

That's just a browser thing.

That's just the browser telling you that you've reached the end. 

Just scroll all the way bottom to THIS page and you'll see this "jump".


I just put in an override. How's that?
