### ISSUE TITLE
Sample Project Page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/lme#17]
Please can you double check the size of the text.

**Comment by markendley** [comment]
Its hard to tell if you're using a much lighter font weight or if the design's type is translucent white
![Screen Shot 2020-05-22 at 11 30 33 pm](https://user-images.githubusercontent.com/6570606/82672903-54c47a00-9c84-11ea-9c17-6e9d17939bb5.png)
![Screen Shot 2020-05-22 at 11 30 22 pm](https://user-images.githubusercontent.com/6570606/82672916-58f09780-9c84-11ea-8c7e-082974735b55.png)

**Comment by markendley** [comment]
sorry was looking at the wrong one. done

**Comment by LaraStudioFriday** [comment]
Can we please make ALL body copy 14 pt - the about us page text is at 16 pt.

**Comment by markendley** [comment]
done
