### ISSUE TITLE
Sample Project page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/lme#18]
Gaps to be tightened up in between image - see Zeplin

**Comment by markendley** [comment]
This isn't close enough?

Below is the design, and below that is the website
![Screen Shot 2020-05-22 at 11 27 55 pm](https://user-images.githubusercontent.com/6570606/82672661-f9928780-9c83-11ea-84ef-a9d82a3859dd.png)
![Screen Shot 2020-05-22 at 11 28 00 pm](https://user-images.githubusercontent.com/6570606/82672666-fb5c4b00-9c83-11ea-88e3-3022c5f1318b.png)

**Comment by markendley** [comment]
sorry was looking at the wrong one. done

**Comment by LaraStudioFriday** [comment]
Just need to make sure the horizontal gaps match the vertical gaps.
<img width="1273" alt="Screen Shot 2020-05-26 at 12 17 39 pm" src="https://user-images.githubusercontent.com/55725505/82854159-f67ced00-9f4a-11ea-891b-769de5ee366d.png">

**Comment by markendley** [comment]
fixed

**Comment by LaraStudioFriday** [comment]
Can the text boxes be in-line with the image boxes.
<img width="414" alt="Screen Shot 2020-05-29 at 9 40 44 am" src="https://user-images.githubusercontent.com/55725505/83204986-9c6d6900-a190-11ea-9e34-a88293d4d812.png">
<img width="443" alt="Screen Shot 2020-05-29 at 9 40 54 am" src="https://user-images.githubusercontent.com/55725505/83204990-a000f000-a190-11ea-893d-23efec054ab7.png">

**Comment by markendley** [comment]
please elabourate

**Comment by Jakestudiofriday** [comment]
![Uploading Screen Shot 2020-05-29 at 12.23.24 pm.png…]()

**Comment by Jakestudiofriday** [comment]
<img width="1372" alt="Screen Shot 2020-05-29 at 12 23 24 pm" src="https://user-images.githubusercontent.com/57921772/83214997-40fba500-a1a9-11ea-90b6-239fc8f3e3c3.png">
