### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/lme#19]
Updated to match Zeplin

**Comment by markendley** [comment]
I need heavier font-weight for this GT-America-Expanded font please

WEB-font

**Comment by LaraStudioFriday** [comment]
Sorry, I meant the menu icon - see attached image.
<img width="1260" alt="Screen Shot 2020-05-26 at 12 07 24 pm" src="https://user-images.githubusercontent.com/55725505/82853972-79517800-9f4a-11ea-9526-bce92c0b85b3.png">

**Comment by markendley** [comment]
oh done.

**Comment by LaraStudioFriday** [comment]
Sorry can you please make it 100% - looks a little transparent.

**Comment by markendley** [comment]
100% white, you got it
