### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/lme#20]
To match the same layout as Zeplin

**Comment by markendley** [comment]
done, gaps are thinner

**Comment by LaraStudioFriday** [comment]
Images need to be square please and laid out like zeplin (journal heading on the left, images on the right)

<img width="1325" alt="Screen Shot 2020-05-26 at 12 05 15 pm" src="https://user-images.githubusercontent.com/55725505/82853765-f03a4100-9f49-11ea-8f78-53af3e1c83ad.png">

**Comment by markendley** [comment]
done

**Comment by LaraStudioFriday** [comment]
Images look positioned too far to the right - can we make the images align to where the project image aligns - see attached image. 
<img width="1260" alt="Screen Shot 2020-05-29 at 10 02 11 am" src="https://user-images.githubusercontent.com/55725505/83206210-b8bed500-a193-11ea-9420-68cbd440713c.png">
<img width="1280" alt="Screen Shot 2020-05-29 at 10 02 37 am" src="https://user-images.githubusercontent.com/55725505/83206223-bf4d4c80-a193-11ea-85d0-9bdd0d254122.png">

**Comment by markendley** [comment]
done
