### ISSUE TITLE
Team page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/lme#22]
To look like Zeplin
<img width="1260" alt="Screen Shot 2020-05-26 at 12 07 24 pm" src="https://user-images.githubusercontent.com/55725505/82853822-0fd16980-9f4a-11ea-81c0-1c3b9c64f6d4.png">

**Comment by markendley** [comment]
.... was this design here before?

Done.

**Comment by LaraStudioFriday** [comment]
More like Zeplin please and yeah it was there before on the last round of changes - with the journal page. 
<img width="445" alt="Screen Shot 2020-05-29 at 9 35 50 am" src="https://user-images.githubusercontent.com/55725505/83204736-e86bde00-a18f-11ea-90ff-29bc68ddcdd7.png">

**Comment by markendley** [comment]
ok ready

I created some more fields for you to use
