### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/lme#23]
Not sure what is going on here?
<img width="947" alt="Screen Shot 2020-05-26 at 12 12 18 pm" src="https://user-images.githubusercontent.com/55725505/82853879-37c0cd00-9f4a-11ea-9089-e763639fabd5.png">

**Comment by markendley** [comment]
I think the reason why it's confusing is because of the align ment of the text, I gave it some padding
also the button gets lost when it's active so I just made it look more like a button

**Comment by LaraStudioFriday** [comment]
The contact page should be looking like Zeplin - just as per the image I sent before. 
Actually - we have now updated this page - see zeplin and attached file. 
<img width="646" alt="Screen Shot 2020-05-29 at 10 07 09 am" src="https://user-images.githubusercontent.com/55725505/83206473-52868200-a194-11ea-8319-3f2166481504.png">

**Comment by markendley** [comment]
done
