### ISSUE TITLE
Project and media PAGES

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/lme#24]
Can we use this effect - https://tympanus.net/Tutorials/CustomCursors/index.html

**Comment by markendley** [comment]
Extra $100

**Comment by LaraStudioFriday** [comment]
Ok, please proceed

**Comment by markendley** [comment]
done

**Comment by LaraStudioFriday** [comment]
It is the actual open box feature - when you click on the image it opens bigger. will chat a video to you

**Comment by markendley** [comment]
Oh THAT feature!

Oh that's a tough one. 

It'll cost $600 +GST

And I'm afraid I won't have time to add that feature, my schedule is really tight until mid-June
