### ISSUE TITLE
Opening animation

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/lme#5]
Just like what did for Hemma - can we do that with lime?

**Comment by markendley** [comment]
1) Black background
2) Lime appears, one character appears after the other
3) then it fades out
4) user has the option to click to skip the animation

$80 +GST

**Comment by Jakestudiofriday** [comment]
Can you keep us updated on your time spent on this project already? I don't want the cost creeping

**Comment by markendley** [comment]
Oh I'm not working on an hourly basis, we agreed on a fixed price?

> $1800 +GST included are 2 revisions, QA and launch

This is a new feature so it'll have to come on top.

**Comment by Jakestudiofriday** [comment]
Ok cool,

can you please add that and also add project name at the bottom ... https://www.fearonhay.com/

**Comment by markendley** [comment]
ready
