### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/lme#6]
Has an error message and doesnt look like the design Jake put together - check zeplin
<img width="370" alt="Screen Shot 2020-01-30 at 12 55 41 pm" src="https://user-images.githubusercontent.com/55725505/73413455-d9029280-435f-11ea-9ee4-1d64879f3882.png">

<img width="662" alt="Screen Shot 2020-01-30 at 12 58 44 pm" src="https://user-images.githubusercontent.com/55725505/73413601-49111880-4360-11ea-9e74-bb637cbee4f6.png">

**Comment by markendley** [comment]
Fixed.

For now on, whenever you wanna page like that, choose the "Plain" page template. 

(and if you want a page with that slider, choose the "Slider" template).
