### ISSUE TITLE
Name of Project

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/lme#7]
Jake to design how this looks over the main project page images - Mark please check out Zeplin

**Comment by LaraStudioFriday** [comment]
http://marke2.sg-host.com/lime/project/
<img width="1200" alt="Screen Shot 2020-05-26 at 12 26 54 pm" src="https://user-images.githubusercontent.com/55725505/82854588-37c1cc80-9f4c-11ea-9801-afbd9d88218a.png">

**Comment by markendley** [comment]
done

**Comment by LaraStudioFriday** [comment]
Please can you make the name smaller - like the sub menu size. 
<img width="270" alt="Screen Shot 2020-05-29 at 9 27 55 am" src="https://user-images.githubusercontent.com/55725505/83204255-b1e19380-a18e-11ea-897e-968111c7bf37.png">

**Comment by markendley** [comment]
done

**Comment by Jakestudiofriday** [comment]
<img width="750" alt="------Screen Shot 2020-05-29 at 12 48 45 pm" src="https://user-images.githubusercontent.com/57921772/83215656-d51a3c00-a1aa-11ea-86e0-8e81bcfc54d1.png">

**Comment by Jakestudiofriday** [comment]
Some reason the projects have shifted
