### ISSUE TITLE
Images arent equal

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/lme#8]
Bottom is taller than the top one - see example
<img width="707" alt="Screen Shot 2020-01-30 at 1 06 16 pm" src="https://user-images.githubusercontent.com/55725505/73413922-58449600-4361-11ea-8fc6-3290b57bcae9.png">

**Comment by markendley** [comment]
rebuilt those sections - how's that?

**Comment by markendley** [comment]
also turned off Retina - we don't need it?

**Comment by Jakestudiofriday** [comment]
Needs retina

**Comment by markendley** [comment]
retina is back
