### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/lme#9]
to match or be similar https://www.seesawstudio.com.au/

**Comment by markendley** [comment]
certainly, what do you think of that?

**Comment by Jakestudiofriday** [comment]
looking good I think it needs a back Navigation - eg menu>project>house at that stage you cant return.

**Comment by markendley** [comment]
ok,... how about that!

(see the arrow)

**Comment by LaraStudioFriday** [comment]
Please can the arrow be the same height as the text. 
<img width="384" alt="Screen Shot 2020-05-29 at 9 32 31 am" src="https://user-images.githubusercontent.com/55725505/83204501-582d9900-a18f-11ea-84e7-057600df8b8a.png">

**Comment by markendley** [comment]
done
